### ISSUE TITLE
Prohibitive sphinx lower bound

### ISSUE THREAD

**Issue by ascillitoe** [tox-dev/sphinx-autodoc-typehints#260]
In https://github.com/tox-dev/sphinx-autodoc-typehints/pull/258 (and version 1.19.3) the `pyproject.toml` was updated to contain:

https://github.com/tox-dev/sphinx-autodoc-typehints/blob/73c6dfe488da724a1d578d6264b94bf89b0e377f/pyproject.toml#L19

Does this mean `sphinx-autodoc-typehints` is now only compatible with the very latest `sphinx` version? Is there a breaking change in `sphinx` that necessitates this?

**Comment by ascillitoe** [comment]
It seems this restrictive sphinx lower bound was first introduced as `Sphinx>=5.1.1` here:

https://github.com/tox-dev/sphinx-autodoc-typehints/commit/ccc75d244d0f4452048f80fc73e39a34a4eefc00#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

**Comment by gaborbernat** [comment]
> Does this mean `sphinx-autodoc-typehints` is now only compatible with the very latest `sphinx` version? Is there a breaking change in `sphinx` that necessitates this?

This is the only version we test for, so it make sense to declare requiring this.

**Comment by gaborbernat** [comment]
Why would you not want to use the latest stable release?

**Comment by jklaise** [comment]
In the ideal world we would, but it's not that simple - even now we have some blockers with newer `sphinx` releases due to latex builds, so we need to pin `sphinx` until we can resolve it. In the meantime if there are improvements in extensions such as `sphinx-autodoc-typehints` that are not breaking changes with older `sphinx` versions then those are most welcome.

I think it's very natural to run on older versions of `sphinx` for many projects until time allows one to update - I wouldn't be surprised that many projects run `sphinx 4.x` with `sphinx-autodoc-typehints`. A restrictive lower bound on a dependency signals that there is some breaking change, but as I understand, it may not be the case here. Lower bounding the requirement to a very recent `sphinx` version without breaking changes being done or reported just means many projects will keep using `1.19.2` until they can upgrade their `sphinx` stack, and not benefit from updates to the extension in the meantime.

**Comment by gaborbernat** [comment]
The problem that as we add changes we never test with older versions so there's no gurantee at all that an older version of sphinx will work with the latest version of sphinx-autodoc-typehints.
