### ISSUE TITLE
Dependency on itself?

### ISSUE THREAD

**Issue by 0-wiz-0** [tox-dev/sphinx-autodoc-typehints#355]
I don't understand this line:

https://github.com/tox-dev/sphinx-autodoc-typehints/blob/d7613ad3beb4d0e90102675b90fff8aad671a446/pyproject.toml#L42

This looks to me like the project has a dependency on itself, but on a newer version than currently exists (1.23.0).
Perhaps this is a misunderstanding, then I'd like an explanation what this means. Thank you!

**Comment by basnijholt** [comment]
I guess this is just some hack to install the dependencies in the docs building CI.

Read The Docs seems to be set up via the UI there.

For the maintainers, there is a toggle you can click to install the package itself.

Otherwise, create a `[.readthedocs.yaml` file](https://docs.readthedocs.io/en/stable/config-file/v2.html) to the repo with appropriate setting.

**Comment by gaborbernat** [comment]
This is a bug PR welcome to remove it.

**Comment by 0-wiz-0** [comment]
Thanks for the feedback, PR submitted.
